## tomcat config
#server.port=8080

# neo4j config
#spring.data.neo4j.username=neo4j
#spring.data.neo4j.password=lab_417
#spring.data.neo4j.uri=http://localhost:7474

spring:
  data:
    neo4j:
      uri: http://localhost:7474
      bolt: bolt://localhost:7687
      username: neo4j
      password: lab_417
    mongodb:
      uri: mongodb://127.0.0.1:27017/KnowledgeGraph

#  main:
server:
  port: 8081
#    allow-bean-definition-overriding: true

geoserver:
  url: http://localhost:8100/geoserver
  username: admin
  password: geoserver
  workspacename: geoserver
  storename: geoserver
  layername: temp
