## tomcat config
#server.port=8080

# neo4j config
#spring.data.neo4j.username=neo4j
#spring.data.neo4j.password=lab_417
#spring.data.neo4j.uri=http://localhost:7474


spring:
  data:
    neo4j:
      uri: http://localhost:7474
      username: neo4j
      password: lab_417
#  main:
server:
  port: 8081
#    allow-bean-definition-overriding: true